version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15
  docker: agilepathway/docker@0.5.2

executors:
  go:
    docker:
      - image: cimg/go:1.14

workflows:
  build-and-publish-docker-image:
    jobs:
      - shellcheck/check
      - compile-mage-scripts
      - docker/hadolint
      - docker/publish:
          requires:
            - compile-mage-scripts
          after_checkout:
            - attach_workspace:
                at: .
          tag_after_build: $(./scripts/after-build-tags.sh)

            
jobs:
  compile-mage-scripts:
    working_directory: ~/agile-pathway-co-uk
    executor: go
    steps:
      - checkout
      - run:
          name: Install Mage
          command: ./scripts/install-mage.sh
      - run:
          name: Install get Gauge version executable
          command: cd go-scripts/src/gauge_version && mage -compile ../../bin/gauge-version -goos linux -goarch amd64
      - run:
          name: Install get Go version executable
          command: cd go-scripts/src/go_version && mage -compile ../../bin/go-version -goos linux -goarch amd64
      - run:
          name: Install get Taiko version executable
          command: cd go-scripts/src/taiko_version && mage -compile ../../bin/taiko-version -goos linux -goarch amd64
      - persist_to_workspace:
          root: .
          paths:
            - go-scripts/bin/*
