version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15
  docker: agilepathway/docker@0.5.2

executors:
  go:
    docker:
      - image: cimg/go:1.14

workflows:
  build-and-publish-docker-image:
    jobs:
      - shellcheck/check
      - compile-mage-scripts
      - docker/hadolint
      - docker/publish:
          requires:
            - compile-mage-scripts
          after_checkout:
            - attach_workspace:
                at: .
            - run: sudo cp -r go-scripts/bin/* /usr/local/bin/
          tag_after_build: $(docker-tags -v)

            
jobs:
  compile-mage-scripts:
    working_directory: ~/agile-pathway-co-uk
    executor: go
    steps:
      - checkout
      - run:
          name: Install Mage
          command: ./scripts/install-mage.sh
      - run:
          name: Install docker-tags executable
          command: mage -compile go-scripts/bin/docker-tags -goos linux -goarch amd64
      - persist_to_workspace:
          root: .
          paths:
            - go-scripts/bin/*
